
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Bell, Loader2, Send } from 'lucide-react';
import { RestockRequest } from '../types';
import { saveRestockRequest } from '../services/dbUtils';

interface RestockModalProps {
    isOpen: boolean;
    onClose: () => void;
    productName: string;
    productId: string;
}

const RestockModal: React.FC<RestockModalProps> = ({ isOpen, onClose, productName, productId }) => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [whatsapp, setWhatsapp] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isSuccess, setIsSuccess] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);

        try {
            const request: RestockRequest = {
                id: '', // Generated by DB
                productId,
                customerName: name,
                customerEmail: email,
                customerWhatsapp: whatsapp,
                date: new Date().toISOString()
            };

            await saveRestockRequest(request);
            setIsSuccess(true);
            setTimeout(() => {
                onClose();
                setIsSuccess(false);
                setName('');
                setEmail('');
                setWhatsapp('');
            }, 2000);
        } catch (error) {
            console.error("Failed to submit request", error);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-stone-900/40 backdrop-blur-sm"
                    />
                    <motion.div
                        initial={{ scale: 0.95, opacity: 0, y: 20 }}
                        animate={{ scale: 1, opacity: 1, y: 0 }}
                        exit={{ scale: 0.95, opacity: 0, y: 20 }}
                        className="relative bg-white rounded-[2rem] p-8 w-full max-w-md shadow-2xl border border-stone-100 overflow-hidden"
                    >
                        {/* Background Decoration */}
                        <div className="absolute top-0 right-0 w-32 h-32 bg-[#C5A059]/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />

                        <button onClick={onClose} className="absolute top-6 right-6 text-stone-300 hover:text-stone-900 transition-colors">
                            <X size={20} />
                        </button>

                        {isSuccess ? (
                            <div className="py-12 flex flex-col items-center text-center space-y-4">
                                <div className="w-16 h-16 bg-green-50 rounded-full flex items-center justify-center text-green-600 mb-4">
                                    <Bell size={32} />
                                </div>
                                <h3 className="text-xl font-bold text-stone-900">Request Received</h3>
                                <p className="text-sm text-stone-500 max-w-[200px]">We will notify you on WhatsApp and Email once this artifact is secured.</p>
                            </div>
                        ) : (
                            <>
                                <div className="mb-8">
                                    <span className="text-[9px] font-black text-[#C5A059] uppercase tracking-widest mb-2 block">Priority Waitlist</span>
                                    <h3 className="text-2xl font-bold text-stone-900 serif italic">Request {productName}</h3>
                                </div>

                                <form onSubmit={handleSubmit} className="space-y-4">
                                    <div>
                                        <input
                                            type="text"
                                            placeholder="Full Name"
                                            required
                                            value={name}
                                            onChange={(e) => setName(e.target.value)}
                                            className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                        />
                                    </div>
                                    <div>
                                        <input
                                            type="email"
                                            placeholder="Email Address"
                                            required
                                            value={email}
                                            onChange={(e) => setEmail(e.target.value)}
                                            className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                        />
                                    </div>
                                    <div>
                                        <input
                                            type="tel"
                                            placeholder="WhatsApp Number"
                                            required
                                            value={whatsapp}
                                            onChange={(e) => setWhatsapp(e.target.value)}
                                            className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                        />
                                    </div>

                                    <button
                                        type="submit"
                                        disabled={isSubmitting}
                                        className="w-full bg-stone-900 text-white p-4 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-[#C5A059] transition-colors flex items-center justify-center space-x-2"
                                    >
                                        {isSubmitting ? (
                                            <Loader2 size={16} className="animate-spin" />
                                        ) : (
                                            <>
                                                <span>Notify Me</span>
                                                <Send size={14} />
                                            </>
                                        )}
                                    </button>
                                </form>
                            </>
                        )}
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
};

export default RestockModal;
