
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Bell, Loader2, Send, Mail, MessageCircle } from 'lucide-react';
import { RestockRequest } from '../types';
import { saveRestockRequest } from '../services/dbUtils';
import { messaging } from '../services/firebaseConfig';

interface RestockModalProps {
    isOpen: boolean;
    onClose: () => void;
    productName: string;
    productId: string;
    user?: any;
}

const RestockModal: React.FC<RestockModalProps> = ({ isOpen, onClose, productName, productId, user }) => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [whatsapp, setWhatsapp] = useState('');
    const [preference, setPreference] = useState<'email' | 'whatsapp'>('email');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isSuccess, setIsSuccess] = useState(false);

    useEffect(() => {
        if (isOpen && user) {
            setName(user.displayName || '');
            setEmail(user.email || '');
            // Default to email if we have it, but user can switch
        } else if (!isOpen) {
            // Reset fields on close if needed, but keeping them might be annoying if accidental close
        }
    }, [isOpen, user]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Validation
        if (preference === 'whatsapp') {
            // Nigerian Phone Validation: +234 or 0 followed by 7,8,9 and 9 digits
            const nigerianPhoneRegex = /^(0|234|\+234)?([789][01]\d{8})$/;
            const cleanNumber = whatsapp.replace(/[\s-]/g, '');
            if (!nigerianPhoneRegex.test(cleanNumber)) {
                alert("Please enter a valid Nigerian WhatsApp number.");
                return;
            }
        }

        setIsSubmitting(true);

        try {

            const request: any = {
                id: '', // Generated by DB
                productId,
                customerName: name,
                notificationChannel: preference,
                date: new Date().toISOString()
            };

            if (preference === 'email') request.customerEmail = email;
            if (preference === 'whatsapp') request.customerWhatsapp = whatsapp;

            await saveRestockRequest(request);
            setIsSuccess(true);
            setTimeout(() => {
                onClose();
                setIsSuccess(false);
                if (!user) {
                    setName('');
                    setEmail('');
                    setWhatsapp('');
                    setPreference('email');
                }
            }, 2000);
        } catch (error: any) {
            console.error("Failed to submit request", error);
            alert(`Failed to save request: ${error.message || error}`);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-stone-900/40 backdrop-blur-sm"
                    />
                    <motion.div
                        initial={{ scale: 0.95, opacity: 0, y: 20 }}
                        animate={{ scale: 1, opacity: 1, y: 0 }}
                        exit={{ scale: 0.95, opacity: 0, y: 20 }}
                        className="relative bg-white rounded-[2rem] p-8 w-full max-w-md shadow-2xl border border-stone-100 overflow-hidden"
                    >
                        {/* Background Decoration */}
                        <div className="absolute top-0 right-0 w-32 h-32 bg-[#C5A059]/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />

                        <button onClick={onClose} className="absolute top-6 right-6 text-stone-300 hover:text-stone-900 transition-colors">
                            <X size={20} />
                        </button>

                        {isSuccess ? (
                            <div className="py-12 flex flex-col items-center text-center space-y-4">
                                <div className="w-16 h-16 bg-green-50 rounded-full flex items-center justify-center text-green-600 mb-4">
                                    <Bell size={32} />
                                </div>
                                <h3 className="text-xl font-bold text-stone-900">Request Received</h3>
                                <p className="text-sm text-stone-500 max-w-[200px]">
                                    We will notify you via {preference === 'whatsapp' ? 'WhatsApp' : 'Email'} once this artifact is secured.
                                </p>
                            </div>
                        ) : (
                            <>
                                <div className="mb-8">
                                    <span className="text-[9px] font-black text-[#C5A059] uppercase tracking-widest mb-2 block">Priority Waitlist</span>
                                    <h3 className="text-2xl font-bold text-stone-900 serif italic">Request {productName}</h3>
                                </div>

                                <div className="flex bg-stone-100 p-1 rounded-xl mb-6">
                                    {(['email', 'whatsapp'] as const).map((type) => (
                                        <button
                                            key={type}
                                            type="button"
                                            onClick={() => setPreference(type)}
                                            className={`flex-1 py-2 rounded-lg text-[10px] font-black uppercase tracking-wider flex items-center justify-center space-x-2 transition-all ${preference === type ? 'bg-white shadow-sm text-stone-900' : 'text-stone-400 hover:text-stone-600'}`}
                                        >
                                            {type === 'email' && <Mail size={14} />}
                                            {type === 'whatsapp' && <MessageCircle size={14} />}
                                            <span className="hidden sm:inline">{type}</span>
                                        </button>
                                    ))}
                                </div>

                                <form onSubmit={handleSubmit} className="space-y-4">
                                    {/* If User is Logged In, we hide Name Input or prefill/disable it */}
                                    {/* User asked to "no need to ask for email and name again" */}
                                    {/* To be safe, we can hide them or show them as readonly text */}
                                    {!user && (
                                        <div>
                                            <input
                                                type="text"
                                                placeholder="Full Name"
                                                required
                                                value={name}
                                                onChange={(e) => setName(e.target.value)}
                                                className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                            />
                                        </div>
                                    )}

                                    {preference === 'email' && (
                                        <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>
                                            {user ? (
                                                <p className="text-xs text-stone-500 px-1">Using email: <strong className="text-stone-900">{email}</strong></p>
                                            ) : (
                                                <input
                                                    type="email"
                                                    placeholder="Email Address"
                                                    required
                                                    value={email}
                                                    onChange={(e) => setEmail(e.target.value)}
                                                    className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                                />
                                            )}
                                        </motion.div>
                                    )}

                                    {preference === 'whatsapp' && (
                                        <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>
                                            <input
                                                type="tel"
                                                placeholder="WhatsApp Number (e.g. 080...)"
                                                required
                                                value={whatsapp}
                                                onChange={(e) => setWhatsapp(e.target.value)}
                                                className="w-full bg-stone-50 border border-stone-100 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-[#C5A059] transition-all"
                                            />
                                            <p className="text-[9px] text-stone-400 mt-2 ml-1">We verify Nigerian (+234) numbers for accuracy.</p>
                                        </motion.div>
                                    )}


                                    <button
                                        type="submit"
                                        disabled={isSubmitting}
                                        className="w-full bg-stone-900 text-white p-4 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-[#C5A059] transition-colors flex items-center justify-center space-x-2"
                                    >
                                        {isSubmitting ? (
                                            <Loader2 size={16} className="animate-spin" />
                                        ) : (
                                            <>
                                                <span>Notify Me</span>
                                                <Send size={14} />
                                            </>
                                        )}
                                    </button>
                                </form>
                            </>
                        )}
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
};


export default RestockModal;
